# Generated by Django 4.0.5 on 2022-06-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_initial'),
    ]

    operations = [
    ]
