# Generated by Django 4.0.5 on 2022-06-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20220608_1205'),
    ]

    operations = [
    ]
