# Generated by Django 4.0.5 on 2022-06-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_image_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='gallery_image',
        ),
        migrations.AddField(
            model_name='image',
            name='image_caption',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
