# Generated by Django 4.0.5 on 2022-06-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20220608_1245'),
    ]

    operations = [
    ]
