# Generated by Django 4.0.5 on 2022-06-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20220608_1252'),
    ]

    operations = [
    ]
