# Generated by Django 4.0.5 on 2022-06-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_subscribers_remove_image_content_like_follow_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='content',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
