# Generated by Django 4.0.5 on 2022-06-08 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_image_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='content',
        ),
    ]
