# Generated by Django 4.0.5 on 2022-06-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20220608_1254'),
    ]

    operations = [
    ]
